### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException: Cannot read field "requestTimeout" because "opts" is null

### ISSUE THREAD

**Issue by costamarco** [agiliumtrade-ai/metaapi-java-sdk#6]
bug in implementation. The construct allow MetaStats without opts argument

example:

import cloud.metaapi.sdk.MetaStats;

String token = "...";
MetaStats metaStats = new MetaStats(token);

**Comment by RomanKisilenko** [comment]
Hello, the above issue was fixed in a recent release.
