### ISSUE TITLE
Timeout exception synchronizing with MetaTrader account

### ISSUE THREAD

**Issue by jprietor** [agiliumtrade-ai/metaapi-java-sdk#8]
MetaApi Java SDK is not synchronizing with MT4 accounts - Last Friday 17th Feb was working fine and today it is not working. I'm getting a TimeoutException every time I call connection.waitSynchronized().get(). I have tried with my real MT4 account and with a MT4 demo account, I have also tried to run code examples from scratch (MetaApiRpcExample) with my accounts IDs and tokens and I have the same issue:

```
Waiting for API server to connect to broker (may take couple of minutes)
Waiting for SDK to synchronize to terminal state (may take some time depending on your history size)
22:52:52,906 INFO  [pool-2-thread-6] MetaApiWebsocketClient.lambda$null$5:452 - MetaApi websocket client connected to the MetaApi server via https://mt-client-api-v1.vint-hill.agiliumtrade.ai dedicated server
22:52:52,923 INFO  [pool-2-thread-6] MetaApiWebsocketClient.lambda$null$5:455 - Please note that it can take up to 3 minutes for your dedicated server to start for the first time. During this time it is OK if you see some connection errors.
java.util.concurrent.ExecutionException: cloud.metaapi.sdk.clients.TimeoutException: Timed out waiting for account MetApi to synchronize to MetaTrader account ***, synchronization id null
```

By the way, running the code examples from node.js SDK with my accounts works fine: Synchronizes and I can see all my positions and orders from my accounts.

**Comment by RomanKisilenko** [comment]
Please contact us via online chat so that we can enable Java SDK compatibility for you.
